// Dependencies
const _ = require('node-validator')

module.exports = _.isObject()
  .withRequired('event_name', _.isString())
  .withOptional('event_description', _.isString())
  .withRequired('start_date', _.isDate())
  .withRequired('end_date', _.isDate())
  .withRequired('location', _.isString())
  .withOptional('event_banner', _.isString())
  .withRequired('status', _.isBoolean())
  .withRequired('organisator', _.isObject()
    .withRequired('user_id', _.isString())
  )
  .withRequired('participants', _.isObject()
    .withRequired('user_id', _.isString())
  )
  .withOptional('photo_album', _.isObject()
    .withRequired('photo', _.isString())
    .withOptional('photo_comments', _.isObject()
      .withRequired('comments', isString())
    )
  )
  .withOptional('tickets', _.isObject()
    .withRequired('ticket_name', _.isString())
    .withRequired('price', _.isNumber())
    .withRequired('amount', _.isNumber())
  )
  .withOptional('event_survey', _.isObject()
    .withRequired('survey', _.isObject()
      .withRequired('question', _.isString())
      .withRequired('number_answer', _.isObject()
        .withRequired('answer', _.isString())
      )
    )
  )